import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.variable} antialiased`}>
      <body className="overflow-x-hidden bg-background">
        <div className="grid min-h-screen grid-rows-[auto_minmax(0,1fr)_auto]">
          <Navbar cartCount={3} />
          <main className="min-h-0 flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
